Section:
  Max Tile: 10  # Maximum vertical and horizontal tiles
  Max Layer: 7  # Maximum layers
  Default Width: 5
  Default Height: 5
  Tile Type: &tile_type
    - "None"
    - "Walkable"
    - "Custom1"
    - "Custom2"  # Different types of placeable tiles


Interactive:
  Height Percentage: 0.5
  Width Percentage: 0.5
  Grid Colour:
    - "gray"
    - "lightgray"
    - "lightblue"
    - "white"
  Tile Colour:
    - "#000000"
    - "#ff0000"
    - "#00ff00"
    - "#0000ff"
  Tile Type:
    *tile_type



